apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Organization
metadata:
    name: org-main-org
    namespace: crossplane-system
    annotations:
        grafana.io/org-name: Main Org.
        crossplane.io/external-name: "1"
    labels:
        managed-by: gitops-sync
        org: main-org
spec:
    deletionPolicy: Orphan
    forProvider:
        name: Main Org.
        createUsers: false
        viewers:
            - testuser@vpbank.com
            - another@vpbank.com
            - brand.new@vpbank.com
            - newuser@vpbank.com
    providerConfigRef:
        name: default
