apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Organization
metadata:
    name: org-payment-team
    namespace: crossplane-system
    labels:
        managed-by: gitops-sync
        org: payment-team
        sync-date: "2026-03-28"
    annotations:
        argocd.argoproj.io/sync-wave: "0"
        grafana.io/org-name: Payment Team
spec:
    forProvider:
        name: Payment Team
        createUsers: true
        admins:
            - test@gmail.com
        viewers:
            - branch@newmember@gmail.com
    providerConfigRef:
        name: default
