apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Organization
metadata:
    name: org-it-cais-dev
    namespace: crossplane-system
    labels:
        managed-by: gitops-sync
        org: it-cais
        sync-date: "2026-03-28"
    annotations:
        grafana.io/org-name: IT-CAIS
spec:
    forProvider:
        name: IT-CAIS
        createUsers: true
    providerConfigRef:
        name: dev
