apiVersion: alerting.grafana.crossplane.io/v1alpha1
kind: AlertruleV0Alpha1
metadata:
  name: plat-api-warn-p99-latency-high
  labels:
    tier: nrt
    severity: warning
    template_id: TPL-ALERT-002
    org: org-platform-2025
  annotations:
    governance.grafana.io/template-id: "TPL-ALERT-002"
    governance.grafana.io/routing-tier: "nrt"
spec:
  providerConfigRef:
    name: default
  forProvider:
    metadata:
      folderUid: plat-nearrealtime
    spec:
      title: "PLAT-API-WARN-p99-latency-high"
      for: "5m"
      execErrState: "Error"
      noDataState: "NoData"
      annotations:
        summary: "P99 latency exceeded 2s SLO on PLAT APIs"
        description: "P99 latency has been above 2 seconds for more than 5 minutes"
        runbook_url: "https://wiki.vpbank.com.vn/runbooks/p99-latency"
      labels:
        tier: "nrt"
        severity: "warning"
        template_id: "TPL-ALERT-002"
        org: "org-platform-2025"
