apiVersion: alerting.grafana.crossplane.io/v1alpha1
kind: RuleGroup
metadata:
    name: rg-it-rtb-df-1m-group
    namespace: crossplane-system
    labels:
        category: capacity
        managed-by: gitops-sync-plugin
        notification-policy: slack-alerts-warning
        owner-team: DF
        severity: warning
        sync-date: "2026-04-01"
        template-id: TPL-ALERT-004
        tier: nrt
    annotations:
        governance.grafana.io/interval-seconds: "60"
        governance.grafana.io/routing-tier: nrt
spec:
    forProvider:
        name: IT-RTB-DF 1m GROUP
        organizationRef:
            name: org-main-org
        folderUid: afhke2bqakvswa
        intervalSeconds: 60
        rule:
            - name: DF-CAPACITY-ALERT
              for: 3m
              noDataState: NoData
              execErrState: Error
              condition: C
              data:
                - datasourceUid: mimir
                  model: '{"datasource":{"type":"prometheus","uid":"mimir"},"expr":"100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100) \u003e 90","instant":false,"intervalMs":60000,"maxDataPoints":43200,"range":true,"refId":"A"}'
                  queryType: range
                  refId: A
                  relativeTimeRange:
                    - from: 600
                      to: 0
                - datasourceUid: __expr__
                  model: '{"conditions":[],"expression":"A","reducer":"last","refId":"B","type":"reduce"}'
                  queryType: ""
                  refId: B
                  relativeTimeRange:
                    - from: 600
                      to: 0
                - datasourceUid: __expr__
                  model: '{"conditions":[{"evaluator":{"params":[0],"type":"gt"},"operator":{"type":"and"},"query":{"params":["B"]},"reducer":{"params":[],"type":"last"},"type":"query"}],"expression":"B","refId":"C","type":"threshold"}'
                  queryType: ""
                  refId: C
                  relativeTimeRange:
                    - from: 600
                      to: 0
              annotations:
                description: Cảnh báo khi CPU usage vượt quá 90% trong 10 phút
                summary: High CPU Usage - Main Org.
              labels:
                category: capacity
                managed-by: gitops-sync-plugin
                notification-policy: slack-alerts-warning
                owner-team: DF
                severity: warning
                sync-date: "2026-04-01"
                template-id: TPL-ALERT-004
                tier: nrt
    providerConfigRef:
        name: default
