apiVersion: v1
kind: Secret
metadata:
  name: grafana-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "url": "http://grafana-prod.monitoring.svc.cluster.local:80",
      "auth": "${GRAFANA_SERVICE_ACCOUNT_TOKEN}"
    }
---
apiVersion: grafana.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: grafana-creds
      key: credentials