apiVersion: alerting.grafana.crossplane.io/v1alpha1
kind: ContactPoint
metadata:
    name: contactpoint-it-rtb-df
    namespace: crossplane-system
    labels:
        managed-by: gitops-sync
        sync-date: "2026-04-02"
    annotations:
        grafana.io/name: IT-RTB-DF
        grafana.io/type: email
        grafana.io/uid: ""
spec:
    forProvider:
        name: IT-RTB-DF
        type: email
        settingsJson: '{"addresses":"test@example.com"}'
    providerConfigRef:
        name: default
