apiVersion: oss.grafana.crossplane.io/v1alpha1
kind: Organization
metadata:
    name: org-platform-2025-dev
    namespace: crossplane-system
    annotations:
        governance.grafana.io/org-name: ORG-Platform-2025
    labels:
        managed-by: gitops-sync
        org: platform-2025
spec:
    deletionPolicy: Delete
    forProvider:
        name: ORG-Platform-2025
        createUsers: true
        admins:
            - noc-lead@vpbank.com.vn
            - sre-lead@vpbank.com.vn
        editors:
            - noc-engineer-1@vpbank.com.vn
            - noc-engineer-2@vpbank.com.vn
            - sre-engineer-1@vpbank.com.vn
        viewers:
            - noc-viewer-1@vpbank.com.vn
            - dev-viewer-1@vpbank.com.vn
    providerConfigRef:
        name: dev
