apiVersion: alerting.grafana.crossplane.io/v1alpha1
kind: RuleGroup
metadata:
  name: main-org-df-capacity-alert
  namespace: crossplane-system
  labels:
    category: capacity
    managed-by: gitops-sync-plugin
    org: main-org
    severity: warning
    tier: standard
    template-id: TPL-ALERT-003
  annotations:
    governance.grafana.io/routing-tier: standard
spec:
  providerConfigRef:
    name: default
  forProvider:
    name: "IT-RTB-DF 5m GROUP"
    folderUid: afhke2bqakvswa
    orgId: 1
    intervalSeconds: 300
    rule:
      - name: "DF-CAPACITY-ALERT"
        for: "15m"
        noDataState: NoData
        execErrState: Error
        condition: C
        annotations:
          description: "Canh bao khi memory usage vuot qua 80%"
          summary: "High Memory Usage - Main Org."
        labels:
          category: capacity
          managed-by: gitops-sync-plugin
          owner-team: DF
          severity: warning
          tier: standard
          template-id: TPL-ALERT-003
        data:
          - refId: A
            datasourceUid: mimir
            queryType: range
            relativeTimeRange:
              - from: 600
                to: 0
            model: '{"expr":"(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80","instant":false,"intervalMs":60000,"maxDataPoints":43200,"range":true,"refId":"A","datasource":{"type":"prometheus","uid":"mimir"}}'
          - refId: B
            datasourceUid: "__expr__"
            queryType: ""
            relativeTimeRange:
              - from: 600
                to: 0
            model: '{"type":"reduce","refId":"B","expression":"A","reducer":"last","conditions":[]}'
          - refId: C
            datasourceUid: "__expr__"
            queryType: ""
            relativeTimeRange:
              - from: 600
                to: 0
            model: '{"type":"threshold","refId":"C","expression":"B","conditions":[{"evaluator":{"type":"gt","params":[0]},"operator":{"type":"and"},"query":{"params":["B"]},"reducer":{"type":"last","params":[]},"type":"query"}]}'
